#!/usr/bin/env python3
"""The address space: what the SoC defines, and what this firmware actually uses.

Two different things, and conflating them is a way to guess:

  nominal   the MCF5441x memory map, from
            docs/contracts/mcf5441x-reference-v1.json, which is what the
            silicon defines whether or not anything uses it.
  actual    the memory regions a running machine has mapped, read from a
            snapshot. That is the firmware's real working set.

Also states where each firmware section loads, taken from the container's own
section table rather than from anywhere else.

    python tools/mk1doc_memory.py --syx Digitakt_OS1.53.syx --out docs/mk1
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dt2 import container as dtc
from emu.snapshot import restore

CONTRACT = 'docs/contracts/mcf5441x-reference-v1.json'


def human(n):
    for unit in ('B', 'KiB', 'MiB', 'GiB'):
        if n < 1024 or unit == 'GiB':
            return '%.0f %s' % (n, unit) if unit != 'B' else '%d B' % n
        n /= 1024.0
    return str(n)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--syx', required=True)
    ap.add_argument('--snapshot',
                    default='snapshots/Digitakt_OS1.53/gui.snap')
    ap.add_argument('--out', default='docs/mk1')
    ap.add_argument('--root', default='.')
    args = ap.parse_args()
    os.makedirs(os.path.join(args.out, 'facts'), exist_ok=True)

    facts = {
        'document': 'digitakt-mk1.memory-map',
        'schema_version': 1,
        'note': 'The nominal map is what the SoC defines; the mapped regions '
                'are what this firmware actually uses. They are different '
                'things and are reported separately.',
    }

    # --- nominal, from the contract --------------------------------------
    cpath = os.path.join(args.root, CONTRACT)
    nominal = []
    if os.path.exists(cpath):
        with open(cpath, encoding='utf-8') as fh:
            nominal = json.load(fh).get('memory_map', [])
    facts['nominal_soc_map'] = nominal

    # --- where the sections load, from the container ----------------------
    _c, secs = dtc.sections(args.syx)
    loads = []
    for sid, off, clen, dest in secs:
        loads.append({
            'section_id': sid,
            'dest_field': '0x%08X' % dest,
            'packed_bytes': clen,
            'is_load_address': dest not in (0x00000000,),
            'note': ('version word, not a load address (dt2/container.py)'
                     if sid == 2 else
                     'dest is 0x00000000 -- NOT a load address; where this '
                     'section loads is not stated by the container'
                     if dest == 0 else ''),
        })
    facts['section_load_addresses'] = loads

    # --- actual, from a snapshot -----------------------------------------
    regions = []
    try:
        m, _extra, _regs = restore(args.snapshot)
        for begin, end, perms in sorted(m.uc.mem_regions()):
            regions.append({
                'start': '0x%08X' % begin,
                'end': '0x%08X' % (end + 1),
                'size_bytes': end - begin + 1,
                'size_human': human(end - begin + 1),
                'perms': perms,
            })
        facts['snapshot'] = os.path.basename(args.snapshot)
    except Exception as exc:                            # noqa: BLE001
        facts['snapshot_error'] = '%s: %s' % (type(exc).__name__, exc)
    facts['mapped_regions'] = regions
    facts['mapped_total_bytes'] = sum(r['size_bytes'] for r in regions)

    jpath = os.path.join(args.out, 'facts', 'memory.json')
    with open(jpath, 'w', encoding='utf-8') as fh:
        json.dump(facts, fh, indent=2)
        fh.write('\n')
    print('wrote %s' % jpath)

    L = []
    A = L.append
    A('# 02 — The address space')
    A('')
    A('Generated by `tools/mk1doc_memory.py`. Machine-readable:')
    A('`facts/memory.json`.')
    A('')
    A('Two different things, reported separately because conflating them is a')
    A('way to guess:')
    A('')
    A('- **nominal** — what the MCF5441x defines, whether or not anything')
    A('  uses it. From `docs/contracts/mcf5441x-reference-v1.json`.')
    A('- **actual** — the regions a running machine has mapped, read from a')
    A('  snapshot. This is the firmware\'s real working set.')
    A('')
    A('## Where the firmware sections load')
    A('')
    A('From the container\'s own section table.')
    A('')
    A('| section id | `dest` | packed | note |')
    A('|---|---|---|---|')
    for s in loads:
        A('| %d | `%s` | %d | %s |'
          % (s['section_id'], s['dest_field'], s['packed_bytes'],
             s['note'] or 'load address'))
    A('')
    A('## Actually mapped (measured)')
    A('')
    if regions:
        A('From `%s`. Total mapped: **%s** across %d regions.'
          % (facts.get('snapshot', '?'), human(facts['mapped_total_bytes']),
             len(regions)))
        A('')
        A('| start | end | size | perms |')
        A('|---|---|---|---|')
        for r in regions:
            A('| `%s` | `%s` | %s | %d |'
              % (r['start'], r['end'], r['size_human'], r['perms']))
    else:
        A('Could not read the snapshot: %s'
          % facts.get('snapshot_error', 'unknown'))
    A('')
    A('## Nominal SoC map')
    A('')
    if nominal:
        A('| region | start | end | description |')
        A('|---|---|---|---|')
        for r in nominal:
            A('| %s | `%s` | `%s` | %s |'
              % (r.get('name'), r.get('start'), r.get('end'),
                 r.get('description', '')))
        A('')
        A('Every row above carries `source` and `source_ref` in the contract;')
        A('see `docs/contracts/mcf5441x-reference-v1.json` for the citation.')
    else:
        A('Contract not found at `%s`.' % CONTRACT)
    A('')
    A('## Fixed points worth knowing')
    A('')
    A('| address | what |')
    A('|---|---|')
    A('| `0x40000000` | VBR — the interrupt vector table (256 vectors). It is')
    A('  written at run time and is **not** in the firmware image |')
    A('| `0x40000400` | MAIN OS load address (section id 3) |')
    A('| `0x03000900` | bootstrap `dest` (section id 2) — but for the')
    A('  bootstrap this field is a version word, not an address |')
    A('| `0x80000400` | updater load address (section id 4) |')
    A('| `0x48000000` | initial stack pointer, per earlier measurement |')
    A('')

    mpath = os.path.join(args.out, '02-memory-map.md')
    with open(mpath, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(L) + '\n')
    print('wrote %s' % mpath)


if __name__ == '__main__':
    main()
